/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html"],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "on-error-container": "#93000a",
          "tertiary": "#000000",
          "on-primary": "#ffffff",
          "outline-variant": "#c5c6cd",
          "on-secondary": "#ffffff",
          "secondary-container": "#194cfe",
          "green-mint": "#10B981",
          "on-tertiary": "#ffffff",
          "on-primary-fixed": "#0d1c32",
          "blue-royal": "#1B4DFF",
          "surface-container-lowest": "#ffffff",
          "on-error": "#ffffff",
          "primary-fixed": "#d6e3ff",
          "on-tertiary-fixed-variant": "#005236",
          "on-background": "#191c1e",
          "surface-container-high": "#e6e8ea",
          "on-primary-container": "#76849f",
          "surface-variant": "#e0e3e5",
          "navy-deep": "#0A192F",
          "error-container": "#ffdad6",
          "surface-dim": "#d8dadc",
          "surface-tint": "#515f78",
          "secondary": "#0036ce",
          "primary-fixed-dim": "#b9c7e4",
          "tertiary-fixed-dim": "#4edea3",
          "surface": "#f7f9fb",
          "inverse-on-surface": "#eff1f3",
          "inverse-surface": "#2d3133",
          "tertiary-fixed": "#6ffbbe",
          "surface-container-highest": "#e0e3e5",
          "tertiary-container": "#002113",
          "error": "#ba1a1a",
          "on-secondary-container": "#dbdeff",
          "surface-bright": "#f7f9fb",
          "on-secondary-fixed-variant": "#0032c3",
          "on-surface": "#191c1e",
          "on-tertiary-container": "#009668",
          "on-secondary-fixed": "#001258",
          "on-primary-fixed-variant": "#39475f",
          "secondary-fixed-dim": "#b9c3ff",
          "surface-container": "#eceef0",
          "border-subtle": "#E2E8F0",
          "primary-container": "#0d1c32",
          "surface-container-low": "#f2f4f6",
          "primary": "#000000",
          "on-surface-variant": "#44474d",
          "secondary-fixed": "#dee1ff",
          "slate-text": "#475569",
          "outline": "#75777e",
          "on-tertiary-fixed": "#002113",
          "background": "#f7f9fb",
          "inverse-primary": "#b9c7e4"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "container-max": "1280px",
          "margin-mobile": "16px",
          "gutter": "24px",
          "margin-desktop": "40px",
          "section-gap": "120px"
      },
      "fontFamily": {
          "headline-md": ["Plus Jakarta Sans"],
          "display-lg": ["Plus Jakarta Sans"],
          "button": ["Inter"],
          "display-lg-mobile": ["Plus Jakarta Sans"],
          "label-caps": ["Inter"],
          "body-lg": ["Inter"],
          "headline-sm": ["Plus Jakarta Sans"],
          "body-md": ["Inter"]
      },
      "fontSize": {
          "headline-md": ["32px", { "lineHeight": "1.3", "letterSpacing": "0.01em", "fontWeight": "600" }],
          "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "0.02em", "fontWeight": "700" }],
          "button": ["14px", { "lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "600" }],
          "display-lg-mobile": ["36px", { "lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "700" }],
          "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600" }],
          "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
          "headline-sm": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
          "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }]
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
